version: "3.8"

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: autoparts-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: autoparts
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - autoparts-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000
        NEXT_PUBLIC_APP_URL: http://localhost:3000
    container_name: autoparts-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database
      MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/autoparts

      # JWT Secrets (change these in production)
      JWT_SECRET: development-jwt-secret-minimum-32-chars
      JWT_REFRESH_SECRET: development-refresh-secret-minimum-32-chars

      # Application URLs
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXT_PUBLIC_APP_URL: http://localhost:3000

      # Email (configure with your SMTP settings)
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_SECURE: false
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      ADMIN_EMAIL: admin@localhost

      # Node Environment
      NODE_ENV: production
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - autoparts-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Admin UI (optional)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: autoparts-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - autoparts-network

volumes:
  mongodb_data:
    driver: local

networks:
  autoparts-network:
    driver: bridge
